[package]
name = "mrrp"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mrrp-audio = { workspace = true, features = ["full"] }
mrrp-core.workspace = true
mrrp-filter = { workspace = true, features = ["full"] }
mrrp-modem.workspace = true
mrrp-util.workspace = true


[[bench]]
name = "buffering"
harness = false

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
criterion = "0.8.2"
dotenvy.workspace = true
futures-util.workspace = true
num-complex.workspace = true
num-traits.workspace = true
pin-project-lite.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true
