[workspace]
resolver = "3"
members = [
    "crates/mrrp",
    "crates/mrrp-adsb",
    "crates/mrrp-audio",
    "crates/mrrp-cli",
    "crates/mrrp-core",
    "crates/mrrp-filter",
    "crates/mrrp-hamlib",
    "crates/mrrp-modem",
    "crates/mrrp-rtl-sdr",
    "crates/mrrp-rtl-sdr-test",
    "crates/mrrp-rtl-tcp",
    "crates/mrrp-sat",
    "crates/mrrp-sdr",
    "crates/mrrp-sstv",
    "crates/mrrp-util",
    "crates/mrrp-widgets",
    "crates/mrrp-xtask",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jgraef/mrrp"

# Include debug info in release, so we can investigate bugs better
[profile.release]
debug = "full"
strip = "none"

# Dependencies can be optimized even for dev builds. we don't mind if they take long to compile (once).
# This usually gives a lot of performance gain over very little extra compilation time.
[profile.dev.package."*"]
opt-level = 3
debug-assertions = false
overflow-checks = false

# Without debug-assertions egui compiles out some methods we want to use (debug overlay)
[profile.dev.package."egui"]
opt-level = 3
debug-assertions = true
overflow-checks = false

# mrrp might benefit from optimizations, but for now we still want checks
[profile.dev.package.mrrp]
opt-level = 3
debug-assertions = true
overflow-checks = true

[workspace.dependencies]
mrrp-audio = { path = "crates/mrrp-audio", default-features = false }
mrrp-core = { path = "crates/mrrp-core", default-features = false }
mrrp-filter = { path = "crates/mrrp-filter", default-features = false }
mrrp-modem = { path = "crates/mrrp-modem", default-features = false }
mrrp-rtl-sdr = { path = "crates/mrrp-rtl-sdr", default-features = false }
mrrp-util = { path = "crates/mrrp-util", default-features = false }
mrrp-widgets = { path = "crates/mrrp-widgets", default-features = false }

# todo: remote and use rtl-sdr-rs instead
rtlsdr-async = { version = "0.1.0", git = "https://github.com/jgraef/rtlsdr-async.git" }

anyhow = "1.0.102"
bytemuck = { version = "1.25.0", default-features = false }
bytes = { version = "1.11.1", default-features = false }
chrono = { version = "0.4.45", default-features = false }
clap = { version = "4.6.1", features = ["derive"] }
derive_more = { version = "2.1.1", default-features = false }
dotenvy = { version = "0.15.7", default-features = false }
egui = { version = "0.34.2", default-features = false }
futures-core = { version = "0.3.32", default-features = false }
futures-util = { version = "0.3.32", default-features = false }
nalgebra = { version = "0.35.0", default-features = false }
num-complex = { version = "0.4.6", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
parking_lot = { version = "0.12.4", default-features = false }
pin-project-lite = { version = "0.2.17", default-features = false }
rand = { version = "0.10.1", default-features = false }
rustfft = "6.4.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_with = "3.21.0"
thiserror = { version = "2.0.18", default-features = false }
tokio = { version = "1.52.3", default-features = false }
tokio-stream = { version = "0.1.18", default-features = false }
tokio-util = { version = "0.7.18", default-features = false }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
