[workspace]
resolver = "3"
members = ["mrrp", "mrrp-cli"]

[profile.dev]
opt-level = 3
overflow-checks = false

[profile.release]
debug = "full"
strip = "none"

[workspace.dependencies.rtlsdr-async]
version = "0.1.0"
#git = "https://github.com/jgraef/rtlsdr-async.git"
path = "../rtlsdr-async/rtlsdr-async"
