[package]
name = "mrrp-sdr"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
chrono = { workspace = true, features = ["serde"] }
clap.workspace = true
colorgrad = { version = "0.8.0", features = ["preset"] }
const_format = "0.2.36"
derive_more = { workspace = true, features = ["debug"] }
directories = "6.0.0"
dotenvy.workspace = true
eframe = { version = "0.34.2", features = ["persistence"] }
egui = { workspace = true, features = ["default"] }
egui-phosphor = "0.12.0"
egui_dock = { version = "0.19.1", features = ["serde"] }
egui_extras = { version = "0.34.2", features = ["all_loaders"] }
futures-util.workspace = true
indexmap = { version = "2.14.0", features = ["serde"] }
mrrp-core.workspace = true
mrrp-audio = { workspace = true, features = ["wav", "rodio"] }
mrrp-rtl-sdr = { workspace = true, features = ["mrrp"] }
mrrp-widgets = { workspace = true, features = ["colorgrad", "serde"] }
num-complex = { workspace = true, features = ["bytemuck"] }
num-traits.workspace = true
parking_lot.workspace = true
rand = { workspace = true, features = ["sys_rng"] }
rand_distr = "0.6.0"
rustfft.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-util = { workspace = true, features = ["rt"] }
toml = "1.1.2"
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu = { version = "29.0.3", features = ["serde"] }
mrrp-util.workspace = true

[build-dependencies]
anyhow.workspace = true
chrono = { workspace = true, features = ["now"] }
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
