[package]
name = "mrrp-widgets"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytemuck.workspace = true
colorgrad = { workspace = true, optional = true, default-features = false }
egui.workspace = true
egui-wgpu = { version = "0.36.2", default-features = false }
nalgebra = { workspace = true, features = ["bytemuck", "std"] }
parking_lot.workspace = true
serde = { workspace = true, optional = true }
tracing.workspace = true
wgpu = { version = "30.0.1", default-features = false }

[features]
colorgrad = ["dep:colorgrad"]
serde = ["dep:serde"]
