[package]
name = "mrrp-file"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitflags = { version = "2.13.2", optional = true }
byteorder = { version = "1.5.0", optional = true }
chrono = { workspace = true, features = ["serde"], optional = true }
ciborium = { version = "0.2.2", optional = true }
derive_more = { workspace = true, features = ["debug"], optional = true }
flate2 = { version = "1.1.10", optional = true }
hound = { version = "3.5.1", optional = true }
mrrp-core.workspace = true
mrrp-geo = { workspace = true, features = ["serde"], optional = true }
mrrp-util = { workspace = true, optional = true }
num-complex.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }
thiserror.workspace = true
tracing.workspace = true

[features]
default = []
full = ["wav", "miq", "riff"]
wav = ["dep:hound", "dep:mrrp-util", "dep:derive_more"]
miq = [
    "dep:bitflags",
    "dep:chrono",
    "dep:ciborium",
    "dep:flate2",
    "dep:serde",
    "dep:mrrp-geo",
]
riff = ["dep:byteorder"]
