[package]
name = "mrrp-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["env"] }
directories = "6.0.0"
dotenvy.workspace = true
futures-util.workspace = true
hexyl = "0.17.0"
humantime = "2.3.0"
mrrp-audio = { workspace = true, default-features = false, features = ["wav"] }
mrrp-core.workspace = true
mrrp-rtl-sdr.workspace = true
mrrp-rtl-tcp.workspace = true
mrrp-sat.workspace = true
mrrp-util = { workspace = true, features = ["sat"] }
num-traits.workspace = true
parking_lot.workspace = true
pin-project-lite.workspace = true
serde = { workspace = true, features = ["derive"] }
tabled = "0.22.0"
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "time",
] }
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
