[package]
name = "mrrp-audio"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mrrp-core.workspace = true
mrrp-file = { workspace = true, features = ["wav"], optional = true }
mrrp-util.workspace = true
parking_lot = { workspace = true, optional = true }
rodio = { version = "0.22.2", optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync"], optional = true }

[features]
default = ["full"]
full = ["wav", "rodio"]
wav = ["dep:mrrp-file"]
rodio = ["dep:rodio", "dep:parking_lot", "dep:tokio"]
