[package]
name = "mrrp-sat"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
chrono = { workspace = true, features = ["serde"] }
clap.workspace = true
derive_more = { workspace = true, features = ["display"] }
directories = "6.0.0"
dotenvy.workspace = true
humantime = "2.3.0"
numeris = { version = "0.5.11", features = ["serde"] }
reqwest = { version = "0.13.3", features = ["json"] }
satkit = { version = "0.18.0", features = ["chrono"] }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
toml = "1.1.2"
tracing.workspace = true
tracing-subscriber.workspace = true
url = { version = "2.5.8", features = ["serde"] }
