[package]
name = "mrrp-xtask"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
colorgrad = { version = "0.8.0", features = ["preset"] }
dotenvy.workspace = true
mrrp-widgets = { workspace = true, features = ["colorgrad", "serde"] }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
